"""empty message

Revision ID: 525eaccb8142
Revises: a5cffa318ac2
Create Date: 2024-05-10 17:27:24.550486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '525eaccb8142'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('nombre_persona', sa.String(length=100), nullable=False),
    sa.Column('peso', sa.Integer(), nullable=False),
    sa.Column('color_de_piel', sa.String(length=20), nullable=False),
    sa.Column('color_de_pelo', sa.String(length=20), nullable=True),
    sa.Column('genero', sa.String(length=20), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_persona')
    )
    op.create_table('planets',
    sa.Column('id_planeta', sa.Integer(), nullable=False),
    sa.Column('nombre_planeta', sa.String(length=100), nullable=False),
    sa.Column('periodo_rotacion', sa.Integer(), nullable=False),
    sa.Column('diametro', sa.Float(), nullable=False),
    sa.Column('clima', sa.String(length=50), nullable=False),
    sa.Column('terreno', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_planeta')
    )
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('planeta_id', sa.Integer(), nullable=True),
    sa.Column('nombre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nombre_id'], ['people.id_persona'], ),
    sa.ForeignKeyConstraint(['planeta_id'], ['planets.id_planeta'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personaje_favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('people_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['people_id'], ['people.id_persona'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planeta_favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('planeta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planeta_id'], ['planets.id_planeta'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planeta_favoritos')
    op.drop_table('personaje_favoritos')
    op.drop_table('favoritos')
    op.drop_table('planets')
    op.drop_table('people')
    # ### end Alembic commands ###
